apiVersion: apps/v1 
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app: spring-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-devops
  template:
    metadata:
      labels:
        app: spring-devops
    spec:
      containers:
      - name: spring-deployment
        image: echaguiller/tarea-devops:latest
        ports:
        - containerPort: 8080
