apiVersion: apps/v1 
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app: spring-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-devops
  template:
    metadata:
      labels:
        app: spring-devops
    spec:
      # serviceAccount: sa1
      containers:
      - name: spring-deployment
        image: echaguiller/tarea-devops:latest
        ports:
        - containerPort: 8085
        imagePullPolicy: Always
